### ISSUE TITLE
Breadcrumb is shifting the whole page to slight right in Obsidian v0.16.0

### ISSUE THREAD

**Issue by Missionary2112** [SkepticMystic/breadcrumbs#435]
**Describe the bug**
Breadcrumb is shifting the whole page to slight right in Obsidian v.016.0

**To Reproduce**
1. Go to `Edit / Live mode`
2. Add `Breadcrumb` in YAML
3. See error: The whole page is shifting to the right

**Expected behavior**
It should not shift the page.

**Screenshots**
- Breadcrumb in YAML
![2022-08-29_22 56 46_CSX](https://user-images.githubusercontent.com/98799613/187361077-ecd21357-74f7-4303-9224-067e30bd338c.jpg)

- No Breadcrumb in YAML
![2022-08-29_22 57 09_CSX](https://user-images.githubusercontent.com/98799613/187360827-d9919cea-dd53-4892-a78c-37b18fca4a95.jpg)

**Desktop (please complete the following information):**
 - MacOS Monterey
 - Version 12.5.1
- Obsidian v.0.16.0

**Comment by JenFau** [comment]
I'm experiencing this, too. Quite a significant shift to the right which makes it impossible to work on a document if in split screen mode. Is temporarily fixed by turning off the Breadcrumbs plugin and turning it back on again.

**Comment by JenFau** [comment]
Document in edit mode before switching to preview mode
<img width="964" alt="Screenshot 2022-09-05 at 18 42 18" src="https://user-images.githubusercontent.com/13613183/188496665-6a259aa9-ecfe-4b1b-8c23-b619b0040b51.png">

Document in preview mode after entering (and exiting) preview mode

<img width="1033" alt="Screenshot 2022-09-05 at 18 42 31" src="https://user-images.githubusercontent.com/13613183/188496695-176a9cc0-1986-49c8-a9eb-24c827371bae.png">

**Comment by kraka40** [comment]
having same issue, turning off plugin is only fix.. even temporarily it only works until page is refreshed.

**Comment by mkasu** [comment]
FYI the plugin does not need to be turned off completely. 

It's just broken in live-preview mode, so I deactivated "Breadcrumbs Settings -> Views -> Trail/Grid/Juggl -> "Show Breadcrumbs in Edit/Live-Preview Mode".

The other modes work fine, I can still use it in reading view. I also still have access to the Breadcrumb Matrix/Breadcrumb Down menus in the sidebar, which I'm mainly using now for navigation. Not ideal, but better than no Breadcrumbs!

**Comment by erikthedeveloper** [comment]
This is what I'm seeing with Obsidian 0.16.2 and Breadcrumbs 3.6.0

![](https://cdn.zappy.app/79853ce6dad8a5c1b36891f7c4198e02.png)

❌ Source Mode
❌ Live Preview
👍 Reading Mode

This appears to be due to `.BC-trail`'s parent `.cm-contentContainer` being `display: flex`

![](https://cdn.zappy.app/c0c24c483496c5c234b915fc5f02f281.png)

I'm not sure if `.cm-contentContainer` is part of Breadcrumbs or not, but one solution could be to:

1. Add `flex-direction: column` to `.cm-contentContainer` (currently unset, defaulting to `row`)
2. Add `width: 100%` to `.cm-content` (currently set to `width: 0` which feels like a potential source of bugs)

This appears to fix the bug for both Source Mode and Live Preview

![](https://cdn.zappy.app/2395226b32fbdca458a73515388488dd.png)

**Comment by erikthedeveloper** [comment]
On a closer look it appears this could be resolved by changing where `.BC-trail` is inserted.

For example updating this line which inserts for both Live Preview and Source Mode

https://github.com/SkepticMystic/breadcrumbs/blob/333b35c2932a2717569575519dee5924139fc9cb/src/Views/TrailView.ts#L239-L239

to something like:

```diff
-view.querySelector("div.cm-contentContainer")?.firstChild?.before(trailDiv)
+view.querySelector("div.cm-contentContainer")?.before(trailDiv)
```

so that the trail is inserted as a sibling of the `display: flex` `.cm-contentContainer` rather than a child of it.

Referencing this larger chunk of logic where the trail UI is created and inserted

https://github.com/SkepticMystic/breadcrumbs/blob/333b35c2932a2717569575519dee5924139fc9cb/src/Views/TrailView.ts#L192-L241

Seen here manually moved in the DevTools:

![](https://cdn.zappy.app/5c8ed18c214d4d20a67975660ad465ea.png)

**Comment by SkepticMystic** [comment]
Thanks to @erikthedeveloper for the PR to resolve this :)
Should be fixed in 3.6.1

**Comment by mkasu** [comment]
Thanks for the fix and PR.

I can confirm the shift isn't happening anymore. However, on my end, it does not use full width in live preview mode, as it does in other modes, making it get very tiny close to the root note:

Live Preview

<img width="838" alt="CleanShot 2022-09-08 at 15 14 33@2x" src="https://user-images.githubusercontent.com/798036/189048332-81390448-21d0-4401-b277-1d3d7508f15a.png">

Reading mode

<img width="748" alt="CleanShot 2022-09-08 at 15 14 39@2x" src="https://user-images.githubusercontent.com/798036/189048405-5c8919f8-3562-4e5d-969a-f17d599fadcb.png">

**Comment by SkepticMystic** [comment]
@mkasu yes, this is true.
Can you open another issue for this?
